GET http://127.0.0.1:8000/api/cfp/dossier/entreprises HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1611|Tm3dl0rJZYG3Sy4QyqNELLUI6ld0uc7vM5vUYTeE8cc9536e



    {
    "email": "responsable@numerika.center",
    "password": "12345678"
    }

